# Zero init
We explore the backpropogation gradients after a single forward pass of a network with weights innitialized to 0

In [16]:
import torch
from torch import nn
relu = nn.functional.relu
t = torch.tensor
import torchinfo

class net(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.w0 = nn.Linear(1, 3, )
        self.w1 = nn.Linear(3, 2)
        self.w2 = nn.Linear(2, 1)

        [(nn.init.zeros_(x.weight), nn.init.zeros_(x.bias)) for x in [self.w0, self.w1, self.w2]]
    
    def forward(self, x):
        return self.w2(relu(self.w1(relu(self.w0(x)))))

network = net()
torchinfo.summary(network)

Layer (type:depth-idx)                   Param #
net                                      --
├─Linear: 1-1                            6
├─Linear: 1-2                            8
├─Linear: 1-3                            3
Total params: 17
Trainable params: 17
Non-trainable params: 0

In [21]:
three = t([3.0])
l = ((network(three) - three) ** 2).sum()
l.backward()

In [22]:
network.w2.weight.grad

tensor([[-0., -0.]])

In [23]:
network.w2.bias.grad

tensor([-6.])

In [24]:
network.w1.weight.grad

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
network.w1.bias.grad

tensor([0., 0.])

In [26]:
network.w.weight.grad

tensor([[0.],
        [0.],
        [0.]])

In [27]:
network.w0.bias.grad

tensor([0., 0., 0.])